Repository AY2223S1-CS2103T-F11-1/tp, pull requests merged in 2022-10, with the labels that each got.

#89 Rename existing edit command to editp
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#91 Implement delete Internship feature (deletei command)
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/DeleteInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/FindInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#92 Implement edit internship feature (editi command)
  src/main/java/seedu/address/logic/commands/EditInternshipCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditInternshipCommandParser.java
Labels: priority.Medium

#105 Update AddressBookParser to be able to parse flags
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task, priority.Medium

#142 Update Commons section and Use cases section in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#140 Add Link Command and Unlink Command
  src/main/java/seedu/address/logic/commands/LinkCommand.java
  src/main/java/seedu/address/logic/commands/UnlinkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LinkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnlinkCommandParser.java
  src/test/java/seedu/address/logic/commands/LinkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnlinkCommandTest.java
Labels: priority.High

#174 Change DeleteInternshipCommand to use -i flag
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteInternshipCommand.java
Labels: type.Task

#177 Update gui result display person and internship card
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Task

#179 Update list person command to use flags
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
Labels: type.Task

#169 Update LinkCommand and UnlinkCommand Success message and Error messages
  src/main/java/seedu/address/logic/commands/LinkCommand.java
  src/main/java/seedu/address/logic/commands/UnlinkCommand.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
Labels: type.Bug

#185 Fix bug: enforce 1 argument in sort -i command
  src/main/java/seedu/address/logic/commands/SortInternshipCommand.java
  src/main/java/seedu/address/logic/commands/SortPersonCommand.java
  src/main/java/seedu/address/logic/parser/SortInternshipCommandParser.java
Labels: type.Bug

#196 Fix link command message usage
  src/main/java/seedu/address/logic/commands/LinkCommand.java
Labels: type.Bug

#197 update build.gradle app name to InterNUS
  build.gradle
Labels: type.Bug

#253 Update UG for v1.4
  docs/UserGuide.md
Labels: type.DocumentationBug

#250 Address Unlink Command Bugs
  src/main/java/seedu/address/logic/commands/UnlinkCommand.java
  src/main/java/seedu/address/logic/parser/UnlinkCommandParser.java
Labels: type.FunctionalityBug

#252 Address personlist/internshiplist not updating after editing linked counterpart
  src/main/java/seedu/address/logic/commands/EditInternshipCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.FunctionalityBug
